### ISSUE TITLE
Ditch versioneer in favor of setuptools-scm

### ISSUE THREAD

**Issue by Rodrigo-Tenorio** [Rodrigo-Tenorio/distromax#31]
Follow [nessai](https://github.com/mj-will/nessai) on this and see how it goes.

**Comment by dbkeitel** [comment]
bilby now also went that way after some discussion (https://git.ligo.org/lscsoft/bilby/-/merge_requests/1118 / https://git.ligo.org/lscsoft/bilby/-/merge_requests/1125 ), so :+1: in general

But note:

> One thing to note with this approach is that when using an editable install (pip install -e .) the version is only updated when the module is installed rather than every time it is imported. I'm not sure how this compares to versioneer.

That seems annoying to me, not sure if there's a workaround.
